-- TEACHER AND COURSE MAPPING SETUP
SET FOREIGN_KEY_CHECKS = 0;

-- Ensure Department Exists
INSERT INTO `departments` (department_code, department_name, status) VALUES ('AD', 'Artificial Intelligence and Data Science', 1) ON DUPLICATE KEY UPDATE status=1;
SET @dept_id = (SELECT id FROM `departments` WHERE department_code = 'AD' LIMIT 1);

-- SECTION 1: TEACHER PROFILES
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('MA1702', 'Dr.UMAMAGESWARI D', 'umamageswarid@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('MA1702', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('MA10119', 'Dr.SARANYA D', 'saranyad@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('MA10119', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('MA10763', 'Dr.REVATHI V M', 'revathivm@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('MA10763', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('MA10986', 'Dr.GOMATHI M', 'gomathim@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('MA10986', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('MA11181', 'Dr.HEMALATHA B', 'hemalathab@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('MA11181', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('PH1653', 'Dr.PONGALI SATHYA PRABU N', 'pongalispn@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('PH1653', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('PH10870', 'Dr.VANITHA K', 'vanithak@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('PH10870', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('PH11153', 'Dr.SANGEETHA K', 'sangeethak@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('PH11153', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('PH11152', 'Dr.PRIYADHARSINI A', 'Priyadharsinia@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('PH11152', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('PH11015', 'Dr.GOPI G', 'gopi@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('PH11015', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('CH1493', 'Dr.SUBHAPRIYA P', 'subhapriyap@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('CH1493', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('CH10314', 'Dr.VISWANATHAN G', 'viswanathan@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('CH10314', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('CH11057', 'Dr.KARUPPUSAMY S', 'karuppusamys@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('CH11057', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('CH1557', 'Dr.VIJAYANAND P S', 'vijayanandps@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('CH1557', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('CH11127', 'Dr.MANIGANDAN S', 'manigandan@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('CH11127', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD10931', 'Mr.BALASAMY K', 'balasamyk@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD10931', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD10945', 'Mr.SATHEESH N P', 'satheeshnp@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD10945', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD11069', 'Mr.PREMKUMAR C', 'premkumar@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD11069', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD11089', 'Mrs.RESHMI T S', 'reshmits@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD11089', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD11114', 'Mrs.MANJU M', 'manju@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD11114', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('EE10721', 'Mrs.GOPIKA N P', 'gopika@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('EE10721', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('EE1747', 'Dr.SRITHA P', 'srithap@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('EE1747', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('EE10619', 'Mrs.MADHUMITHA J', 'madhumithaj@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('EE10619', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('EE10616', 'Mrs.NITHYA G', 'nithyag@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('EE10616', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('EE1437', 'Dr.VEERAKUMAR S', 'veerakumars@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('EE1437', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('EC10827', 'Dr.MURUGAN K', 'murugank@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('EC10827', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('EC10813', 'Ms.SHARMILA A', 'sharmilaa@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('EC10813', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('EC10739', 'Dr.ARULMURUGAN L', 'arulmurugan@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('EC10739', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('EC11010', 'Mrs.MARIAAMUTHA R', 'mariaamuthar@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('EC11010', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('CD11061', 'Mrs.PREETHIMATHI L', 'preethimathi@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('CD11061', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('EC10972', 'Mr.VELLINGIRI A', 'vellingiria@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('EC10972', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('CB10949', 'Mrs.MADHUMITHA A', 'madhumithaa@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('CB10949', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('HU11085', 'Dr.SAGUNTHALA DEVI P', 'sagunthaladevi@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('HU11085', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('HU11115', 'Ms.KAMALI D', 'kamali@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('HU11115', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('HU11154', 'Mr.SHYAMSUNDAR S', 'shyamsundar@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('HU11154', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('HU11125', 'Dr.GAYATHRI G M', 'gayathri@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('HU11125', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('HU11139', 'Dr.ASLIN JERUSHA D', 'aslinjerusha@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('HU11139', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('HU11141', 'Dr.EZHIL G', 'ezhil@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('HU11141', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('MA1327', 'Dr.THULASIMANI T', 'thulasimanit@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('MA1327', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('MA11028', 'Mr.SURESH R', 'sureshr@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('MA11028', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('MA11122', 'Dr.AKALYADEVI K', 'akalyadevi@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('MA11122', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD10953', 'Mr.RAJ KUMAR V S', 'rajkumarvs@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD10953', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD10955', 'Ms.ESAKKI MADURA E', 'esakkimadurae@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD10955', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD10928', 'Mrs.NISHA DEVI K', 'nishadevik@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD10928', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD11041', 'Mrs.ASHFORN HERMINA J M', 'ashfornherminajm@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD11041', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD10628', 'Dr.ARUN KUMAR R', 'arunkumarr@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD10628', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD10818', 'Dr.ESWARAMOORTHY V', 'eswaramoorthyv@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD10818', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD11068', 'Ms.BENITA GRACIA THANGAM J', 'benitagraciathangam@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD11068', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD11164', 'Mr.SASSON TAFFWIN MOSES S', 'sassontaffwinmosess@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD11164', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD11019', 'Mrs.KIRUTHIGA R', 'kiruthigar@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD11019', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD11026', 'Mr.CHOZHARAJAN P', 'chozharajanp@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD11026', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD11023', 'Mrs.VAANATHI S', 'vaanathi@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD11023', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD11104', 'Mrs.KALPANA R', 'kalpana@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD11104', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD10838', 'Mrs.NITHYAPRIYA S', 'nithyapriyas@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD10838', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD11096', 'Dr.SUBBULAKSHMI M', 'subbulakshmi@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD11096', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD11016', 'Mr.SATHEESHKUMAR S', 'satheeshkumars@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD11016', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD1444', 'Dr.GOMATHI R', 'gomathir@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD1444', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD11111', 'Ms.SURIYA V', 'suriya@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD11111', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD1108', 'Dr.SUNDARA MURTHY S', 'sundaramurthys@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD1108', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD11009', 'Mrs.DIVYABARATHI P', 'divyabarathip@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD11009', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('CH1894', 'Dr.MALATHI MAHALINGAM', 'malathimahalingamm@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('CH1894', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('CH10957', 'Dr.DEEPHA V', 'deephav@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('CH10957', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('HU11151', 'Dr.NITHYA S', 'nithyas@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('HU11151', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD11042', 'Mrs.JEEVITHA S V', 'jeevithasv@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD11042', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD11116', 'Ms.PRIYADHARSHNI S', 'priyadharshni@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD11116', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD11112', 'Mrs.HEMA PRIYA D', 'hemapriyad@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD11112', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD10936', 'Mr.PRABANAND S C', 'prabanandsc@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD10936', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AD11169', 'Mrs.MANOCHITRA A S', 'manochitra@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AD11169', @dept_id) ON DUPLICATE KEY UPDATE status=1;
INSERT INTO `teachers` (faculty_id, name, email) VALUES ('AM10971', 'Mr.NITHIN P', 'nithinp@bitsathy.ac.in') ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email);
INSERT INTO `department_teachers` (teacher_id, department_id) VALUES ('AM10971', @dept_id) ON DUPLICATE KEY UPDATE status=1;

-- SECTION 2: TEACHER-COURSE ALLOCATION
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'MA1702' FROM `courses` WHERE course_code = '22MA201' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'MA10119' FROM `courses` WHERE course_code = '22MA201' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'MA10763' FROM `courses` WHERE course_code = '22MA201' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'MA10986' FROM `courses` WHERE course_code = '22MA201' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'MA11181' FROM `courses` WHERE course_code = '22MA201' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'PH1653' FROM `courses` WHERE course_code = '22PH202' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'PH10870' FROM `courses` WHERE course_code = '22PH202' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'PH11153' FROM `courses` WHERE course_code = '22PH202' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'PH11152' FROM `courses` WHERE course_code = '22PH202' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'PH11015' FROM `courses` WHERE course_code = '22PH202' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'CH1493' FROM `courses` WHERE course_code = '22CH203' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'CH10314' FROM `courses` WHERE course_code = '22CH203' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'CH11057' FROM `courses` WHERE course_code = '22CH203' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'CH1557' FROM `courses` WHERE course_code = '22CH203' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'CH11127' FROM `courses` WHERE course_code = '22CH203' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD10931' FROM `courses` WHERE course_code = '22GE002' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD10945' FROM `courses` WHERE course_code = '22GE002' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11069' FROM `courses` WHERE course_code = '22GE002' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11089' FROM `courses` WHERE course_code = '22GE002' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11114' FROM `courses` WHERE course_code = '22GE002' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'EE10721' FROM `courses` WHERE course_code = '22GE003' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'EE1747' FROM `courses` WHERE course_code = '22GE003' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'EE10619' FROM `courses` WHERE course_code = '22GE003' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'EE10616' FROM `courses` WHERE course_code = '22GE003' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'EE1437' FROM `courses` WHERE course_code = '22GE003' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'EC10827' FROM `courses` WHERE course_code = '22AI206' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'EC10813' FROM `courses` WHERE course_code = '22AI206' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'EC10739' FROM `courses` WHERE course_code = '22AI206' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'EC11010' FROM `courses` WHERE course_code = '22AI206' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'CD11061' FROM `courses` WHERE course_code = '22AI206' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'EC10972' FROM `courses` WHERE course_code = '22AI206' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'CB10949' FROM `courses` WHERE course_code = '22AI206' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'HU11085' FROM `courses` WHERE course_code = '22HS006' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'HU11115' FROM `courses` WHERE course_code = '22HS006' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'HU11154' FROM `courses` WHERE course_code = '22HS006' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'HU11085' FROM `courses` WHERE course_code = '22HS006' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'HU11115' FROM `courses` WHERE course_code = '22HS006' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'HU11154' FROM `courses` WHERE course_code = '22HS006' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'HU11125' FROM `courses` WHERE course_code = '22HS201' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'HU11139' FROM `courses` WHERE course_code = '22HS201' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'HU11141' FROM `courses` WHERE course_code = '22HS201' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'MA1327' FROM `courses` WHERE course_code = '22AI401' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'MA11028' FROM `courses` WHERE course_code = '22AI401' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'MA10763' FROM `courses` WHERE course_code = '22AI401' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'MA11122' FROM `courses` WHERE course_code = '22AI401' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD10953' FROM `courses` WHERE course_code = '22AI402' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD10955' FROM `courses` WHERE course_code = '22AI402' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11089' FROM `courses` WHERE course_code = '22AI402' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD10928' FROM `courses` WHERE course_code = '22AI402' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11041' FROM `courses` WHERE course_code = '22AI402' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11114' FROM `courses` WHERE course_code = '22AI402' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD10628' FROM `courses` WHERE course_code = '22AI403' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD10818' FROM `courses` WHERE course_code = '22AI403' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11068' FROM `courses` WHERE course_code = '22AI403' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11164' FROM `courses` WHERE course_code = '22AI403' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11019' FROM `courses` WHERE course_code = '22AI404' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11026' FROM `courses` WHERE course_code = '22AI404' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11023' FROM `courses` WHERE course_code = '22AI404' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11104' FROM `courses` WHERE course_code = '22AI404' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD10838' FROM `courses` WHERE course_code = '22AI405' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11096' FROM `courses` WHERE course_code = '22AI405' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11016' FROM `courses` WHERE course_code = '22AI405' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD10931' FROM `courses` WHERE course_code = '22AI405' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD1444' FROM `courses` WHERE course_code = '22AI043' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11111' FROM `courses` WHERE course_code = '22AI043' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD1108' FROM `courses` WHERE course_code = '22AI002' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11009' FROM `courses` WHERE course_code = '22AI002' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'CH1894' FROM `courses` WHERE course_code = '22HS007' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'CH1557' FROM `courses` WHERE course_code = '22HS007' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'CH10957' FROM `courses` WHERE course_code = '22HS007' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'CH11127' FROM `courses` WHERE course_code = '22HS007' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'HU11125' FROM `courses` WHERE course_code = '22HS008' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'HU11139' FROM `courses` WHERE course_code = '22HS008' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'HU11141' FROM `courses` WHERE course_code = '22HS008' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'HU11151' FROM `courses` WHERE course_code = '22HS008' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11042' FROM `courses` WHERE course_code = '22AI601' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11164' FROM `courses` WHERE course_code = '22AI601' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11069' FROM `courses` WHERE course_code = '22AI601' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11009' FROM `courses` WHERE course_code = '22AI602' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD10928' FROM `courses` WHERE course_code = '22AI602' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11026' FROM `courses` WHERE course_code = '22AI602' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11116' FROM `courses` WHERE course_code = '22AI602' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11068' FROM `courses` WHERE course_code = '22AI603' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD10945' FROM `courses` WHERE course_code = '22AI603' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11112' FROM `courses` WHERE course_code = '22AI603' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11041' FROM `courses` WHERE course_code = '22AI020' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD10936' FROM `courses` WHERE course_code = '22AI049' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11169' FROM `courses` WHERE course_code = '22AI049' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11019' FROM `courses` WHERE course_code = '22AI025' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AM10971' FROM `courses` WHERE course_code = '22AI025' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11096' FROM `courses` WHERE course_code = '22AI032' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11023' FROM `courses` WHERE course_code = '22AI032' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD10955' FROM `courses` WHERE course_code = '22AI035' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11042' FROM `courses` WHERE course_code = '22AI036' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD10955' FROM `courses` WHERE course_code = '22AI029' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11016' FROM `courses` WHERE course_code = '22AIH09' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);
INSERT INTO `teacher_course_allocation` (course_id, teacher_id) SELECT id, 'AD11116' FROM `courses` WHERE course_code = '22AIH10' LIMIT 1 ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id);

SET FOREIGN_KEY_CHECKS = 1;