CREATE TABLE IF NOT EXISTS `mark_entry_extension_requests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `window_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `teacher_id` VARCHAR(45) NOT NULL,
  `department_id` INT DEFAULT NULL,
  `semester` INT DEFAULT NULL,
  `exam_type` VARCHAR(100) DEFAULT NULL,
  `requester_username` VARCHAR(100) NOT NULL,
  `requester_role` VARCHAR(50) NOT NULL,
  `reason` TEXT NOT NULL,
  `requested_end_at` DATETIME NOT NULL,
  `status` ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending',
  `approver_username` VARCHAR(100) DEFAULT NULL,
  `approved_end_at` DATETIME DEFAULT NULL,
  `rejection_reason` TEXT DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_mer_window` (`window_id`),
  KEY `idx_mer_teacher_course` (`teacher_id`, `course_id`),
  KEY `idx_mer_status` (`status`),
  KEY `idx_mer_requester` (`requester_username`),
  CONSTRAINT `fk_mer_window` FOREIGN KEY (`window_id`) REFERENCES `mark_entry_windows` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_mer_course` FOREIGN KEY (`course_id`) REFERENCES `courses` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;