ALTER TABLE student_elective_exemption_requests
ADD COLUMN professional_elective_no INT DEFAULT NULL AFTER request_type;

ALTER TABLE student_elective_exemption_requests
DROP COLUMN elective_semester_no;
