CREATE TABLE IF NOT EXISTS student_elective_exemption_requests (
    id INT NOT NULL AUTO_INCREMENT,
    student_id INT NOT NULL,
    student_email VARCHAR(255) NOT NULL,
    request_type VARCHAR(32) NOT NULL,
    elective_semester_no INT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'submitted',
    online_course_name VARCHAR(255) DEFAULT NULL,
    course_type VARCHAR(255) DEFAULT NULL,
    industry_name VARCHAR(255) DEFAULT NULL,
    sector VARCHAR(255) DEFAULT NULL,
    industry_address TEXT DEFAULT NULL,
    city VARCHAR(120) DEFAULT NULL,
    state VARCHAR(120) DEFAULT NULL,
    postal_code VARCHAR(30) DEFAULT NULL,
    country VARCHAR(120) DEFAULT NULL,
    industry_website_url VARCHAR(500) DEFAULT NULL,
    start_date DATE DEFAULT NULL,
    end_date DATE DEFAULT NULL,
    course_duration_weeks INT DEFAULT NULL,
    number_of_days_attended INT DEFAULT NULL,
    stipend_amount DECIMAL(12,2) DEFAULT NULL,
    certificate_file_path VARCHAR(500) DEFAULT NULL,
    certificate_url VARCHAR(1000) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_seer_student_id (student_id),
    KEY idx_seer_request_type (request_type),
    KEY idx_seer_created_at (created_at),
    CONSTRAINT fk_seer_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
